services:
  config-service:
    image: config-service
    container_name: config_service
    ports:
      - 8888:8888
    environment:
      - BPL_JVM_THREAD_COUNT=50
      #      - BPL_DEBUG_ENABLED=true
      #      - BPL_DEBUG_PORT=8001
      - SPRING_CLOUD_CONFIG_SERVER_GIT_URI=https://github.com/daviag/bs-config-repo.git

  catalog-service:
    depends_on:
      - bs-postgres
      - config-service
    image: catalog-service
    container_name: catalog-service
    ports:
      - 9001:9001
    environment:
      - BPL_JVM_THREAD_COUNT=50
#      - BPL_DEBUG_ENABLED=true
#      - BPL_DEBUG_PORT=8001
      - SPRING_DATASOURCE_URL=jdbc:postgresql://bs-postgres:5432/bsdb_catalog
      - SPRING_PROFILES_ACTIVE=testdata

  bs-postgres:
    image: postgres:16-alpine
    container_name: bs-postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
#      - POSTGRES_DB=bsdb_catalog
    volumes:
      - ../postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql
