services:

  bs-ui:
    image: "ghcr.io/polarbookshop/polar-ui:v1"
    container_name: "bs-ui"
    ports:
      - 9004:9004
    environment:
      - PORT=9004

  config-service:
    image: config-service
    container_name: config_service
    ports:
      - 8888:8888
    environment:
      - BPL_JVM_THREAD_COUNT=50
      #      - BPL_DEBUG_ENABLED=true
      #      - BPL_DEBUG_PORT=8001
      - SPRING_CLOUD_CONFIG_SERVER_GIT_URI=https://github.com/daviag/bs-config-repo.git

  catalog-service:
    depends_on:
      - fluent-bit
      - bs-postgres
      - config-service
      - bs-keycloak
    image: catalog-service
    container_name: catalog-service
    ports:
      - 9001:9001
    environment:
      - BPL_JVM_THREAD_COUNT=50
#      - BPL_DEBUG_ENABLED=true
#      - BPL_DEBUG_PORT=8001
      - SPRING_DATASOURCE_URL=jdbc:postgresql://bs-postgres:5432/bsdb_catalog
      - SPRING_PROFILES_ACTIVE=testdata
      - SPRING_CLOUD_CONFIG_URI=http://config-service:8888
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI=http://host.docker.internal:8080/realms/Bookshop
    logging:
      driver: fluentd
      options:
        fluentd-address: 127.0.0.1:24224

  order-service:
    depends_on:
      - bs-postgres
      - config-service
      - bs-keycloak
    image: order-service
    container_name: order-service
    ports:
      - 9002:9002
    environment:
      - BPL_JVM_THREAD_COUNT=50
      #      - BPL_DEBUG_ENABLED=true
      #      - BPL_DEBUG_PORT=8001
      - SPRING_R2DBC_URL=r2dbc:postgresql://bs-postgres:5432/bsdb_order
      - SPRING_FLYWAY_URL=jdbc:postgresql://bs-postgres:5432/bsdb_order
      - SPRING_CLOUD_CONFIG_URI=http://config-service:8888
      - BS_CATALOG_SERVICE_URI=http://catalog-service:9001
      - SPRING_RABBITMQ_HOST=bs-rabbitmq
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI=http://host.docker.internal:8080/realms/Bookshop

  edge-service:
    depends_on:
      - config-service
      - bs-redis
      - bs-keycloak
    image: edge-service
    container_name: edge-service
    ports:
      - 9000:9000
    environment:
      - BPL_JVM_THREAD_COUNT=50
      #      - BPL_DEBUG_ENABLED=true
      #      - BPL_DEBUG_PORT=8001
      - SPRING_CLOUD_CONFIG_URI=http://config-service:8888
      - SPRING_DATA_REDIS_HOST=bs-redis
      - CATALOG_SERVICE_URL=http://catalog-service:9001
      - ORDER_SERVICE_URL=http://order-service:9002
      - SPA_URL=http://bs-ui:9004
      - SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_ISSUER_URI=http://host.docker.internal:8080/realms/Bookshop

  dispatcher-service:
    depends_on:
      - bs-rabbitmq
      - order-service
    image: dispatcher-service
    container_name: dispatcher-service
    ports:
      - 9003:9003
    environment:
      - SPRING_CLOUD_CONFIG_URI=http://config-service:8888
      - SPRING_RABBITMQ_HOST=bs-rabbitmq

  bs-postgres:
    image: postgres:16-alpine
    container_name: bs-postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
#      - POSTGRES_DB=bsdb_catalog
    volumes:
      - ./postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql

  bs-redis:
    image: redis:7.4-alpine
    container_name: bs-redis
    ports:
      - 6379:6379

  bs-rabbitmq:
    image: rabbitmq:3.10-management
    container_name: bs-rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf

  bs-keycloak:
    image: quay.io/keycloak/keycloak:25.0
    container_name: bs-keycloak
    command: start-dev --import-realm
    volumes:
      - ./keycloak:/opt/keycloak/data/import
    environment:
      - KEYCLOAK_ADMIN=user
      - KEYCLOAK_ADMIN_PASSWORD=password
    ports:
      - 8080:8080

  grafana:
    image: grafana/grafana:9.1.2
    container_name: grafana
    depends_on:
      - loki
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=user
      - GF_SECURITY_ADMIN_PASSWORD=password
    volumes:
      - ./observability/grafana/datasources/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
      - ./observability/grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./observability/grafana/grafana.ini:/etc/grafana/grafana.ini

  loki:
    image: grafana/loki:2.6.1
    container_name: loki
    depends_on:
      - fluent-bit
    ports:
      - "3100:3100"

  fluent-bit:
    image: grafana/fluent-bit-plugin-loki:2.6.1-amd64
    container_name: fluent-bit
    ports:
      - "24224:24224"
    environment:
      - LOKI_URL=http://loki:3100/loki/api/v1/push
    volumes:
      - ./observability/fluent-bit/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf