services:
  config-service:
    image: config-service
    container_name: config_service
    ports:
      - 8888:8888
    environment:
      - BPL_JVM_THREAD_COUNT=50
      #      - BPL_DEBUG_ENABLED=true
      #      - BPL_DEBUG_PORT=8001
      - SPRING_CLOUD_CONFIG_SERVER_GIT_URI=https://github.com/daviag/bs-config-repo.git

  catalog-service:
    depends_on:
      - bs-postgres
      - config-service
    image: catalog-service
    container_name: catalog-service
    ports:
      - 9001:9001
    environment:
      - BPL_JVM_THREAD_COUNT=50
#      - BPL_DEBUG_ENABLED=true
#      - BPL_DEBUG_PORT=8001
      - SPRING_DATASOURCE_URL=jdbc:postgresql://bs-postgres:5432/bsdb_catalog
      - SPRING_PROFILES_ACTIVE=testdata
      - SPRING_CLOUD_CONFIG_URI=http://config-service:8888

  order-service:
    depends_on:
      - bs-postgres
      - config-service
    image: order-service
    container_name: order-service
    ports:
      - 9002:9002
    environment:
      - BPL_JVM_THREAD_COUNT=50
      #      - BPL_DEBUG_ENABLED=true
      #      - BPL_DEBUG_PORT=8001
      - SPRING_R2DBC_URL=r2dbc:postgresql://bs-postgres:5432/bsdb_order
      - SPRING_FLYWAY_URL=jdbc:postgresql://bs-postgres:5432/bsdb_order
      - SPRING_CLOUD_CONFIG_URI=http://config-service:8888
      - BS_CATALOG_SERVICE_URI=http://catalog-service:9001
      - SPRING_RABBITMQ_HOST=bs-rabbitmq

  edge-service:
    depends_on:
      - config-service
      - bs-redis
    image: edge-service
    container_name: edge-service
    ports:
      - 9000:9000
    environment:
      - BPL_JVM_THREAD_COUNT=50
      #      - BPL_DEBUG_ENABLED=true
      #      - BPL_DEBUG_PORT=8001
      - SPRING_CLOUD_CONFIG_URI=http://config-service:8888
      - SPRING_DATA_REDIS_HOST=bs-redis
      - CATALOG_SERVICE_URL=http://catalog-service:9001
      - ORDER_SERVICE_URL=http://order-service:9002

  bs-dispatcher-service:
    depends_on:
      - bs-rabbitmq
      - order-service
    image: dispatcher-service
    container_name: dispatcher-service
    ports:
      - 9003:9003
    environment:
      - SPRING_RABBITMQ_HOST=bs-rabbitmq

  bs-postgres:
    image: postgres:16-alpine
    container_name: bs-postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
#      - POSTGRES_DB=bsdb_catalog
    volumes:
      - ./postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql

  bs-redis:
    image: redis:7.4-alpine
    container_name: bs-redis
    ports:
      - 6379:6379

  bs-rabbitmq:
    image: rabbitmq:3.10-management
    container_name: bs-rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf