apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/daviag/bs-catalog-service/k8s?ref=5c00919f47b122598cf5789f5d12e674bd8a9e41

patchesStrategicMerge:
- patch-env.yml
- patch-resources.yml
- patch-volumes.yml

configMapGenerator:
- behavior: merge
  files:
  - application-prod.yml
  name: catalog-config

images:
- name: catalog-service
  newName: ghcr.io/daviag/catalog-service
  newTag: 5c00919f47b122598cf5789f5d12e674bd8a9e41

replicas:
- count: 2
  name: catalog-service
